networks:
  rustdesk-net:
    external: false
services:
  rustdesk:
    ports:
      - 31114:31114
      - 31115:31115
      - 31116:31116
      - 31116:31116/udp
      - 31117:31117
      - 31118:31118
      - 31119:31119
    image: lejianwen/rustdesk-server-s6:latest
    environment:
      - RELAY=<relay_server[:port]>
      - ENCRYPTED_ONLY=1
      - MUST_LOGIN=N
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=<id_server[:31116]>
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=<relay_server[:31117]>
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://<api_server[:31114]>
    volumes:
      - /data/rustdesk/server:/data
      - /data/rustdesk/api:/app/data #将数据库挂载
      - /data/rustdesk/server:/app/conf/data #挂载key文件到api容器，可以不用使用 RUSTDESK_API_RUSTDESK_KEY
    networks:
      - rustdesk-net
    restart: unless-stopped